### ISSUE TITLE
show simple example of loading a file (This does not seem to actually have "same API . . .")

### ISSUE THREAD

**Issue by bdklahn** [vpodpecan/pysbgn#1]
This does not seem to be true:
"The read/write API is the same as in libsbgn-python so you can use the examples from [libsbgn-python documentation](https://libsbgn-python.readthedocs.io/en/latest/examples.html#Create-SBGN)."

There appears to be no "utils" module, in this module, nor in the sbgn_core, used here.

It seems natural for one of the very first things in this documentation to be to show how to load an sbgn file.

See: [https://libsbgn-python.readthedocs.io/en/latest/examples.html#Read-SBGN-from-file](https://libsbgn-python.readthedocs.io/en/latest/examples.html#Read-SBGN-from-file)

**Comment by bdklahn** [comment]
Ah. I see . . . utils is not included.
So we still have to use two packages to do anything useful.
Why not just include that as dependency, or try to collaborate with Matthias to update his? (When I met him, he seemed very nice).
Ok.

**Comment by vpodpecan** [comment]
Basically, my goal was to add as little as possible on top of the generateDS output. I left out `utils` because it's dead simple and not really needed. The `render` module, however, depends on an external service which may or may not work.
